name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Run a multi-line script
      run: |
          git config --global user.email "release_bot@example.com"
          git config --global user.name "Generic Release Bot"
          BRANCH_NAME=br-`date +%s`
          git switch --create $BRANCH_NAME
          date >> foo.txt
          git add foo.txt
          git commit -m "update"
          git push origin $BRANCH_NAME:$BRANCH_NAME
